name: spa

type: nodejs:18

size: S

build:
    flavor: none

dependencies:
  nodejs:
    n: "*"

variables:
  env:
    N_PREFIX: /app/.global

web:
    commands:
        start: sleep
    locations:
        "/":
            root: "public"
            index:
                - "index.html"
            scripts: false
            expires: 10m

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash

        n auto

        hash -r